// Torque Input Map File
if (isObject(moveMap)) moveMap.delete();
new ActionMap(moveMap);
moveMap.bind(keyboard, "escape", escape_key);
moveMap.bind(keyboard, "ctrl w", celebrationWave);
moveMap.bind(keyboard, "ctrl s", celebrationSalute);
moveMap.bind(keyboard, "ctrl k", suicide);
moveMap.bind(keyboard, "n", net_graph);
moveMap.bind(keyboard, "f3", startRecordingDemo);
moveMap.bind(keyboard, "f4", stopRecordingDemo);
moveMap.bind(keyboard, "f5", toggleParticleEditor);
moveMap.bind(keyboard, "f7", dropPlayerAtCamera);
moveMap.bind(keyboard, "f8", dropCameraAtPlayer);
moveMap.bind(keyboard, "w", moveforward_1);
moveMap.bind(keyboard, "s", movebackward_1);
moveMap.bind(keyboard, "a", turnleft_1);
moveMap.bind(keyboard, "d", turnright_1);
moveMap.bind(keyboard, "q", moveleft_1);
moveMap.bind(keyboard, "e", moveright_1);
moveMap.bind(keyboard, "space", jump);
moveMap.bind(keyboard, "up", moveforward_2);
moveMap.bind(keyboard, "down", movebackward_2);
moveMap.bind(keyboard, "left", turnleft_2);
moveMap.bind(keyboard, "right", turnright_2);
moveMap.bind(keyboard, "pageup", spellbank_pageup);
moveMap.bind(keyboard, "pagedown", spellbank_pagedn);
moveMap.bind(keyboard, "i", interruptSpellcastingAction);
moveMap.bind(keyboard, "f", castGreatBall);
moveMap.bind(keyboard, "ctrl d", inflictDamageAction);
moveMap.bind(keyboard, ";", pushPhraseTester);
moveMap.bind(keyboard, "ctrl ;", haltPhraseTester);
moveMap.bind(keyboard, "v", toggleFreeLook);
moveMap.bind(keyboard, "alt c", toggleCamera);
moveMap.bind(keyboard, "z", toggleZoom);
moveMap.bind(keyboard, "home", stepTo);
moveMap.bind(keyboard, "end", stepFro);
moveMap.bind(keyboard, "ctrl o", bringUpOptions);
moveMap.bind(keyboard, "h", toggle_ui_controls);
moveMap.bind(keyboard, "t", nextSeleStyle);
moveMap.bind(keyboard, "shift t", prevSeleStyle);
moveMap.bind(keyboard, "ctrl minus", fireKey);
moveMap.bind(keyboard, "ctrl =", fireAltKey);
moveMap.bind(keyboard, "m", fx_triggerTest);
moveMap.bind(keyboard, "tab", toggleFirstPersonPOV);
moveMap.bind(mouse0, "xaxis", yaw);
moveMap.bind(mouse0, "yaxis", pitch);
moveMap.bind(mouse0, "button0", mouse_btn0);
moveMap.bind(mouse0, "button1", mouse_btn1);
